#!/bin/bash
# Add entry to sorted list.
# Copyright (C) 2019-2022 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

filename="$1"
entry="$2"
details="$3"
newfile="$filename.new"

if [ ! -e "$filename" ]
then
  echo "Error: file '$filename' does not exist."
  exit 2
fi

grep --quiet "$entry" "$filename"
if [ $? -eq 0 ]
then
  echo "File '$filename' already contains entry '$entry'."
  [ "$details" != "" ] && grep "$entry" "$filename"
  exit 0
fi

if [ "$details" != "" ]
then
  line="$entry $details"
else
  line="$entry"
fi

sort --merge "$filename" <(echo "$line") > "$newfile"
diff=$(diff "$newfile" "$filename" | wc --lines)

if [ "$diff" -ne "2" ]
then
  echo "Something went wrong adding '$entry' to '$filename'; diff:"
  diff "$newfile" "$filename"
  exit 1
fi

mv "$filename" "$filename.bak"
mv "$newfile" "$filename"
echo 'Done!'
