#!/bin/bash
# Launcher script for Call of Duty 4: Modern Warfare, running through Wine
# Copyright (C) 2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# bin - full path of the Wine executable
# data - Wine prefix folder
# log - log folder

source winesrc "cod4"

if [ "$1" == "install" ]
then
  myinitprefix

  myinstall "./setup.exe"
elif [ "$1" == "patch" ]
then
  myinstall "./CoD4MW_dd_patch_1.7.exe"
elif [ "$1" == "multi" ]
then
  mydir="drive_c/Program Files/Activision/Call of Duty 4 - Modern Warfare"
  mylaunch "$mydir" "./iw3mp.exe"
else
  mydir="drive_c/Program Files/Activision/Call of Duty 4 - Modern Warfare"
  mylaunch "$mydir" "./iw3sp.exe"
fi
