#!/bin/bash
# Launcher script for Call of Duty: World at War, running through Wine
# Copyright (C) 2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# bin - full path of the Wine executable
# data - Wine prefix folder
# log - log folder

source winesrc "cod5"

if [ "$1" == "install" ]
then
  myinitprefix

  mywinetricks "d3dx9"
  mywinetricks "ie7"

  myinstall "./CodWorldAtWar.exe"
elif [ "$1" == "patch" ]
then
  myinstall "./CoDWaW_patch_v1.2_dd.exe"
  myinstall "./CoDWaW-1.2-1.4-PatchSetup_dd.exe"
  myinstall "./CoDWaW_1.4to1.5_ddsetup.exe"
  myinstall "./CoDWaW-1.5-1.6-Patch_ddsetup.exe"
  myinstall "./CoDWaW-1.6-1.7-PatchSetup_dd.exe"
elif [ "$1" == "edit" ]
then
  REG=$(cat <<EOF
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{fac23f48-31f5-45a8-b49b-5225d61401aa}]
@="\"XAudio2\"
\n"

[HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{fac23f48-31f5-45a8-b49b-5225d61401aa}\InProcServer32]
@="C:\\\\WINDOWS\\\\system32\\\\XAudio2_0.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{6f6ea3a9-2cf5-41cf-91c1-2170b1540063}]
@="AudioReverb"

[HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{6f6ea3a9-2cf5-41cf-91c1-2170b1540063}\InProcServer32]
@="C:\\\\WINDOWS\\\\system32\\\\XAudio2_0.dll"
"ThreadingModel"="Both"
EOF
     )
  echo "${REG}" > cod5-edit.reg
  myrun "regedit" "cod5-edit.reg"
elif [ "$1" == "multi" ]
then
  mydir="drive_c/Program Files/Activision/Call of Duty - World at War"
  mylaunch "$mydir" "./CoDWaWmp.exe"
else
  mydir="drive_c/Program Files/Activision/Call of Duty - World at War"
  mylaunch "$mydir" "./CoDWaW.exe"
fi
