#!/bin/bash
# Helper script to test connection to Internet or given site.
# Copyright (C) 2014-2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ "$1" == "" ]
then
  site="speedtest.net"
else
  site="$1"
fi

start=`date`
successful=0;
fail=`date`
failures=0;

while true
do
  ping "$1" -c 10
  if [ $? == 0 ]
  then
    successful=`expr $successful + 1`;
    fail=`date`;
    failures=0;
  else
    failures=`expr $failures + 1`;
    start=`date`
    successful=0;
  fi

  if [ $successful != 0 ]
  then
    echo "Successful connections since '$start': $successful";
  fi

  if [ $failures != 0 ]
  then
    echo "Failed connections since '$fail': $failures";
  fi
  sleep 10;
done
