#!/bin/bash
# Helper script to install and update Emacs packages.
# Copyright (C) 2015-2017 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

validArgs=("basedir")
source loadconf "$HOME/.scott_script/emacs" "packages.cfg" validArgs[@]

github=(
  "winterTTr/ace-jump-mode"
  "abo-abo/ace-window"
  "vermiculus/apiwrap.el"
  "abo-abo/avy"
  "Bruce-Connor/aggressive-indent-mode"
  "auto-complete/auto-complete"
  "mina86/auto-dim-other-buffers.el"
  "company-mode/company-mode"
  "michaelklishin/cucumber.el"
  "magnars/dash.el"
  "dengste/doc-present"
  "Silex/docker.el"
  "emacs-pe/docker-tramp.el"
  "spotify/dockerfile-mode"
  "editorconfig/editorconfig-emacs"
  "sprang/emacs-2048"
  "501st-alpha1/emacs-auto-formatter"
  "jwiegley/emacs-chess"
  "kiwanami/emacs-deferred"
  "syohex/emacs-git-gutter"
  "jschaf/emacs-lorem-ipsum"
  "tkf/emacs-request"
  "vibhavp/emacs-xkcd"
  "emacsmirror/emms"
  "rejeep/f.el"
  "501st-alpha1/facebook"
  "lewang/fic-mode"
  "lewang/flx"
  "flycheck/flycheck"
  "dominikh/go-mode.el"
  "magit/ghub"
  "vermiculus/ghub-plus"
  "sshaw/git-link"
  "magit/git-modes"
  "emacsmirror/git-timemachine"
  "DarwinAwardWinner/ido-ubiquitous"
  "nonsequitur/inf-ruby"
  "purcell/less-css-mode"
  "magit/magit"
  "magit/magit-annex"
  "jtatarik/magit-gitflow"
  "vermiculus/magithub"
  "kazu-yamamoto/Mew"
  "mattkeller/mk-project"
  "Bruce-Connor/names"
  "OmniSharp/omnisharp-emacs"
  "org-trello/org-trello"
  "magit/orgit"
  "bbatsov/persp-projectile"
  "nex3/perspective-el"
  "lujun9972/pocket-api.el"
  "lujun9972/pocket-mode"
  "auto-complete/popup-el"
  "bbatsov/projectile"
  "pashky/restclient.el"
  "jwiegley/ruby-mode"
  "magnars/s.el"
  "NicolasPetton/seq.el"
  "mbunkus/simple-rtm"
  "thieman/soundcloud.el"
  "magit/ssh-agency"
  "rolandwalker/string-utils"
  "501st-alpha1/twittering-mode"
  "dougm/vagrant-tramp"
  "fxbois/web-mode"
  "magit/with-editor"
  "yoshiki/yaml-mode"
  "magit/magit-popup"
)
third_party=(
  "jblevins.org/git/deft.git"
  "jblevins.org/git/markdown-mode.git"
  "orgmode.org/org-mode.git"
  "orgmode.org/org-sync.git"
)

function loadRepo() {
  url=$1
  if [ "${url:(-4)}" == ".git" ]
  then
    baseurl="${url:0:(-4)}"
  else
    baseurl=$url
  fi
  IFS='/' read -ra array <<< "$baseurl"
  len=${#array[@]}
  last=$(expr $len - 1)
  dir=$(echo ${array[$last]} | sed 's/\./-/g')

  if [ -d $dir ]
  then
    if [ $update -eq 0 ]
    then
      echo "Folder exists, skipping $url..."
    else
      pushd "$dir" > /dev/null
      git pull
      popd > /dev/null
      echo "Updated $dir"; echo;
    fi
  else
    git clone $url
    if [ "$dir" != "${array[$last]}" ]
    then
      mv "${array[$last]}" "$dir"
    fi
  fi
}

if [ ! -d "$basedir" ]
then
  echo "Variable basedir is incorrectly configured."
  echo "It is '$basedir'."
  echo "It should be a folder."

  exit 1
fi

cd $basedir

if [ "$1" == "--no-update" ]
then
  update=0
else
  update=1
fi

if [ $update -eq 1 ]
then
  echo "Running ssh-add, please unlock once, if necessary."
  ssh-add -l > /dev/null
  if [ "$?" -ne 0 ]
  then
    ssh-add
  fi
fi

for name in ${github[*]}
do
  loadRepo ssh://git@github.com/$name
done

for url in ${third_party[*]}
do
  loadRepo git://$url
done

# FIXME: flycheck tests cause load errors.
if [ -d "flycheck/test" ]
then
   rm -rf flycheck/test
fi

pushd org-mode
make autoloads
popd

if [ ! -d "no-repos" ]
then
  mkdir no-repos
fi
cd no-repos

norepoarray=("http://www.emacswiki.org/emacs/download/csharp-mode.el" "http://www.emacswiki.org/emacs/download/csv-mode.el" "http://www.emacswiki.org/emacs/download/notify.el")

for file in ${norepoarray[*]}
do
  IFS='/' read -ra newarray <<< "$file"
  num=${#newarray}
  test=${newarray[$num]}
  if [ -f "$test" ]
  then
    echo "File exists, skipping $test"
  else
    wget $file
  fi
done

if [ ! -d "erc-5.3-extras" ]
then
  wget http://ftp.gnu.org/old-gnu/erc/erc-5.3-extras.zip
  unzip erc-5.3-extras.zip
else
  echo "Folder exists, skipping erc-chess."
fi
