#!/bin/bash
# Helper script to launch Emacs daemon
# Copyright (C) 2014-2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

validArgs=("basedir")
source loadconf "$HOME/.scott_script/emacs" "daemon.cfg" validArgs[@]

if [ "$1" != "--no-update" ]
then
  echo "Running ssh-add, please unlock once, if necessary."
  ssh-add -l > /dev/null
  if [ "$?" -ne 0 ]
  then
    ssh-add
  fi

  if [ -d "$basedir" ]
  then
    cd "$basedir"
    echo "Updating plugins..."
    for i in *
    do
      if [ -d "$i" ] && [ "$i" != "no-repos" ]
      then
        pushd "$i" > /dev/null
        git pull
        popd > /dev/null
        echo "Updated $i"; echo;
      fi
    done
    echo "Updating finished."; echo;
    echo "-----"; echo;
  else
    echo "Variable basedir is incorrectly configured."
    echo "It is $basedir."
    echo "It should be a folder."
  fi
fi

emacs --daemon
