#!/bin/bash
# A script to launch the Firefox web browser.
# Copyright (C) 2013-2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ffexec=/usr/bin/firefox
profilefolder="$HOME/.mozilla/firefox"
profiles="$profilefolder/profiles.ini"
noremote=""
profile=""

function usage() {
  echo "Usage: firefox [profile name]"
  echo "Also supports standard Firefox command-line options."
  echo
  exit 1
}

if [ "$#" -eq "1" ]
then
  case "$1" in
    "help")
      usage
      ;;
    "profiles")
      $ffexec --no-remote --ProfileManager
      exit 0
      ;;
    *)
      profile="${1^}"
      noremote="--no-remote"
      check=`cat "$profiles" | grep "Name" | grep "$profile"`
      if [ -z "$check" ]
      then
        echo "Profile \"$profile\" doesn't exist!"
        exit 2
      fi
      ;;
  esac
else
  $ffexec "$@"
fi

$ffexec $noremote -P $profile

