#!/bin/bash
# A script to launch the Firefox web browser.
# Copyright (C) 2013 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ffexec=/usr/bin/firefox

function usage() {
  echo "Usage: firefox [google|default]"
  echo
  exit 1
}

if [ "$1" == "" ]
then
  $ffexec -P "Scott"
elif [ "$1" == "-P" ] && [ "$2" == "Scott" ]
then
  $ffexec -P "Scott"
elif [ "$1" == "google" ]
then
  $ffexec --no-remote -P "Google"
elif [ "$1" == "default" ]
then
  $ffexec --no-remote -P "default"
else
  usage
fi
