#!/bin/bash
# Add a Firefox saved webpage to the Git index.

function usage() {
  echo "Usage: $(basename $0) <saved>"
  echo
  echo 'Given a saved webpage from Firefox, <saved>, where Firefox saves the'
  echo 'main contents to <saved>.html and the supporting files to the'
  echo '<saved>_files directory, add plaintext files to Git index, and add '
  echo 'binary files to git-annex.'
  echo
  echo 'FIXME: not implemented'
}

if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == 'help' ]
then
  usage
  exit 0
fi

if [ ! -f "$1.html" ]
then
  echo "Error: could not find file '$1.html'"
  usage
  exit 1
fi

tocheck=("$1_files")
plain=("$1.html")
binary=()

while true
do
  current="${tocheck[0]}"
  [ "$current" == '' ] && break
  for filename in "$current"/*
  do
    if [ -d "$filename" ]
    then
      tocheck+=("$filename")
    elif [[ "$filename" == *".txt" ]] || [[ "$filename" == *".html" ]] ||
           [[ "$filename" == *".js" ]] || [[ "$filename" == *".css" ]] ||
           [ "$(basename $filename)" == 'js' ] || [ "$(basename $filename)" == 'v3' ]
    then
      plain+=("$filename")
    elif [[ "$filename" == *".jpg" ]] || [[ "$filename" == *".png" ]] ||
           [[ "$filename" == *".mp4" ]] || [[ "$filename" == *".jpeg" ]]
    then
      binary+=("$filename")
    else
      echo 'Detected unknown file extension!'
      echo "$filename"
      exit 2
    fi
  done

  # Remove first item after processing.
  tocheck=("${tocheck[@]:1}")
done

usage
