#!/bin/bash
# Initialize or enable Dropbox remote for git-annex (via rclone).
# Copyright (C) 2020 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ "$1" == "" ]
then
  echo "Error: missing repository name (for Dropbox subfolder)."
  exit 1
fi

name="$1"

git annex initremote dropbox-rclone type=external externaltype=rclone \
    target=dropbox "prefix=git-annex-files/$name" encryption=shared \
    mac=HMACSHA512 \
    || git annex enableremote dropbox-rclone

git config --int remote.dropbox-rclone.annex-cost 250
