#!/bin/bash
# Get local git-annex file for given remote filename.
# Copyright (C) 2020 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# TODO: Add some error checking.

# $1: full filename, in form 'XXX/YYY/ZZZZZZZ.txt/ZZZZZZZ.txt'

git annex find . --in here --and --in keybase-rsync | while read filename
do
  remotename=$(git-annex-get-remote-filename "$filename")
  if [ "$remotename" == "$1" ]
  then
    echo "$filename"
    break
  fi
done
