#!/bin/bash
# Helper script to sync files via git
# Copyright (C) 2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# FIXME: this shouldn't be hard-coded
cd /mnt/data/documents/todo-list

while true
do
    git commit -a -m "auto-commit at `date`"

    git remote update
    localCommit=`git rev-parse @`
    remoteCommit=`git rev-parse @{u}`
    base=`git merge-base @ @{u}`

    if [ "$localCommit" == "$remoteCommit" ]
    then
        echo "Up-to-date"
    elif [ "$localCommit" == "$base" ]
    then
        git pull
    elif [ "$remoteCommit" == "$base" ]
    then
        git push
    else
        echo "Local and remote have diverged. Attempting automatic resolution."
        git pull
        if [ "$?" -eq 0 ]
        then
            echo "Successfully resolved."
            git push
        else
            echo -e "\a"
            break;
        fi
    fi

    sleep 60
done
