#!/bin/bash
# Launcher script for GRC's SQRL client, running through Wine
# Copyright (C) 2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

bin="/opt/wine/bin/wine-1.7.39/wine"
data="/opt/wine/data/grc-sqrl"
log="/opt/wine/log"

export WINEPREFIX="$data"
export WINEARCH="win32"

name="grc-sqrl"

function myrun() {
  [ -z "$1" ] && echo "Error, missing argument for executable." && return 1

  if [ -z "$2" ]
  then
    "$bin" "$1" >> "$log/$name" 2>&1
  else
    "$bin" "$1" "$2" >> "$log/$name" 2>&1
  fi
}

function mylaunch() {
  [ -z "$1" ] && echo "Error, missing launcher folder." && return 1
  [ -z "$2" ] && echo "Error, missing launcher executable." && return 1
  cd "$data/$1"
  myrun "$2" "$3"
}

mydir="drive_c/Program Files/GRC/SQRL"
if [ "$1" == "install" ]
then
  myinitprefix

  mkdir -p "$data/$mydir"
  cp --verbose ./sqrl*.exe "$data/$mydir/sqrl.exe"
  echo "To set up Firefox to work with this script, do the following:"
  echo "  1. Open 'about:config'."
  echo "  2. Set 'network.protocol-handler.expose.sqrl' to the boolean 'false'."
  echo "  3. Click an SQRL link, and choose this script in the dialog box."
  # TODO look into automating this, by modifying prefs.js, etc.
else
  mylaunch "$mydir" "./sqrl.exe" "$1"
fi
