#!/bin/bash
# Helper script for parsing status of KBFS
# Copyright (C) 2019 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Requires:
# - jq
# - keybase

username=$(keybase status --json | jq --raw-output '.Username')

function get_unflushed() {
  jq '.Journal.UnflushedPaths | length' /keybase/private/$username/.kbfs_status
  return $?
}

function queue_is_empty() {
  unflushed=$(get_unflushed)
  if [ $? -ne 0 ]
  then
    echo 'Error getting status, sleeping just in case.'
    return 2
  fi

  if [ $unflushed -eq 0 ]
  then
    return 0
  else
    echo "$unflushed items are in queue, sleeping.";
    return 1
  fi
}

# Call this to continuously sleep until UnflushedPaths queue is empty.
function wait_for_queue() {
  while ! queue_is_empty
  do
    sleep 10
  done
}

case "$1" in
  'get')
    get_unflushed
    ;;
  'wait')
    wait_for_queue
    ;;
  *)
    echo 'Usage: kbfs-status <get|wait>'
    ;;
esac
