#!/bin/bash
# Wrapper script for Ledger-CLI.

basedir="$(pwd)"

validArgs=('disable_payee_check' 'net_excludes')
source loadconf "$basedir" "led.conf" validArgs[@]

# TODO: Make this configurable.
ledger="$basedir/main.ledger"

args=('--file' "$ledger" '--strict' '--explicit')

if [ "$disable_payee_check" != 1 ]
then
  args+=('--check-payees')
fi

function make_net() {
  # TODO: Make included accounts configurable?
  args+=('balance' '(^Assets' '^Liabilities)' 'and' 'not' 'budget')

  for exclude in "${net_excludes[@]}"
  do
    args+=('and' 'not' "$exclude")
  done
}

if [ "$1" == "net" ]
then
  shift

  make_net
fi

PAGER='' ledger "${args[@]}" "$@"
