#!/bin/bash
# A script to launch Minecraft.
# Copyright (C) 2013 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

validArgs=("mcpath" "magicver")
source loadconf "$HOME/.scott_script/minecraft" "config" validArgs[@]

function usage() {
  echo "Usage: minecraft [vanilla|spout]"
  echo
  exit 1
}

if [ "$1" == "" ]
then
  java -jar "$mcpath/MagicLauncher_$magicver.jar"
elif [ "$1" == "vanilla" ]
then
  java -jar $mcpath/minecraft.jar
elif [ "$1" == "spout" ]
then
  java -jar $mcpath/Spoutcraft.jar
elif [ "$1" == "edit" ]
then
  cd $mcpath/MCEdit/mcedit
  ./mcedit.py
else
  usage
fi

