#!/bin/bash
# Mount helper script.
# Copyright (C) 2013 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

configfolder="$HOME/.scott_script/mounter"
configfile="config"
validArgs=("user" "ip")

source loadconf "$configfolder" "$configfile" validArgs[@]

sambaoptions="username=\"$user\",rw,nosuid,nodev,uhelper=udisks,shortname=mixed,uid=1000,gid=1000,utf8=1,dmask=0077,exec,flush"

echo "sudo mount -t smbfs -o $sambaoptions //$ip/SharedDocs /mnt/desktop-shared.docs"
