#!/bin/bash
# Script to batch rename files.
# Copyright (C) 2013-2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Escape colons (':')
s1="${1//:/\:}"
s2="${2//:/\:}"

#Escape single quotes
s1="${1//'/\'}"
s2="${2//'/\'}"

#Do stuff
find | while read f
do
  if [ $f == "." ]
  then
    continue
  elif [ $f == ".." ]
  then
    continue
  else
    sed "s:$s1:$s2:" --in-place $f
  fi
done
