#!/bin/bash
# Launcher script for Need for Speed III: Hot Pursuit, running through Wine
# Copyright (C) 2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function myrun() {
  if [ "$1" == "" ]
  then
    echo "Fail"
    return 1
  fi

  "$bin" "$1" "$2" >> "$log/nfs3" 2>&1
}

validArgs=("bin" "data" "log")

source loadconf "$HOME/.scott_script/wine" "nfs3.cfg" validArgs[@]

export env WINEPREFIX="$data" WINEARCH=win32

if [ "$1" == "install" ]
then
  echo "First, ensure Wine prefix has been initialized."
  myrun "winecfg"
  echo "Now install"
  cd "/mnt/cdrom/setup/english"
  myrun "setup.exe"
  echo "Install should be complete."
else
  cd "$data/drive_c/Program Files/Electronic Arts/Need For Speed III"
  myrun "nfs3.exe" "-d3d0"
fi

