#!/bin/bash
# Launcher script for Need for Speed: World, running through Wine
# Copyright (C) 2013-2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# bin - full path of the Wine executable
# data - Wine prefix folder
# log - log folder

function myrun() {
  if [ "$1" == "" ]
  then
    echo "Fail"
    return 1
  fi

  "$bin" "$1" >> "$log/nfsw" 2>&1
}

validArgs=("bin" "data" "log")

source loadconf "$HOME/.scott_script/wine" "nfsw.cfg" validArgs[@]

export WINEPREFIX="$data"
export WINEARCH="win32"

if [ "$1" == "install" ]
then
  echo "First, ensure prefix is initialized."
  myrun winecfg

  echo "Winetricks stuff"
  WINE="$bin" winetricks d3dx9 dotnet20 ie7 glsl-enable gdiplus >> "$log/nfsw" 2>&1
  myrun wineboot

  echo "Now install"
  myrun ./setup_nfsw.exe

  echo "Install should have been successful. If not, check the logs and run again."
else
  cd "$data/drive_c/Program Files/Electronic Arts/Need For Speed World"
  WINEPREFIX="$data" "$bin" ./GameLauncher.exe >> "$log/nfsw" 2>&1
fi
