#!/bin/bash
# Save the given nostr event to file.

if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == 'help' ]
then
  echo "Usage: echo <some-event> | $(basename $0) [basedir]"
  echo
  echo "<some-event> is a Nostr event (in JSON)."
  echo
  echo '[basedir] is (optionally) a directory the event should be stored under.'
  echo 'If not given, the current directory will be used as the basedir.'
  echo 'The event will be written to a JSON file under the basedir, with prefix'
  echo 'subfolders.  E.g., for ID of abcdef123, the event will be written to:'
  echo './ab/cd/abcdef123.json'
  echo
  echo 'Multiple events may be saved, just pass one event per line.'
  echo 'Tip: you can pipe the output from `nostcat` directly to this script!'

  exit 0
fi

if [ "$1" != '' ]
then
  if [ -d "$1" ]
  then
    cd "$1"
  else
    echo "Given basedir '$1' is not a valid directory, aborting."
    exit 1
  fi
fi

while read -r line
do
  # Drop ephermal query filter.
  line=$(echo "$line" | jq --compact-output '[.[0], .[2]]')

  id=$(echo "$line" | jq --raw-output '.[1].id')
  firstTwo="${id:0:2}"
  nextTwo="${id:2:2}"

  mkdir --parents "$firstTwo/$nextTwo"

  echo "$line" | jq --sort-keys . > "$firstTwo/$nextTwo/${id}.json"
done
