#!/bin/bash
# Save all of user's nostr events to files.

if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == 'help' ]
then
  echo "Usage: $(basename $0) <pubkey>"
  echo
  echo "Save all nostr events for user <pubkey> to files."
  echo
  echo "Calls `nostr-save-event` on each event, see that script for details."

  exit 0
fi

pubkey="$1"

if [ "$pubkey" == '' ]
then
  echo "Error: no pubkey given, exiting."
  exit 1
fi

# TODO: customizable (and multiple) relays.
queryArgs=('--authors' "$pubkey")

nostril-query "${queryArgs[@]}" | \
  nostcat wss://relay.damus.io | \
  while read -r line
  do
    echo "$line" | nostr-save-event
  done
