#!/bin/bash
# Save all of user's nostr events to files.

if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ "$1" == 'help' ]
then
  echo "Usage: $(basename $0) <pubkey> [--since <date>] [--relays <relayfile>] [--basedir <dir>] [--pubbasedir <dir>]"
  echo
  echo "Save all nostr events for user <pubkey> to files."
  echo
  echo 'If --since <date> given, only request events after given date from '
  echo 'relay(s).  <date> must be parsable by `date`.'
  echo -n 'FIXME: this requires use of currently unmerged PR '
  echo 'https://github.com/jb55/nostril/pull/29 for nostril-query.'
  echo
  echo 'If --relays <relayfile> given, use `<relayfile>` as a JSON file with '
  echo 'relay data.  Should contain a list of items, where each item has the '
  echo 'following properties: `url` (the websocket URL of the relay), `read` '
  echo '(whether user reads from that relay, i.e. if yes then search for '
  echo 'interacted-with data there), and `write` (whether the user writes '
  echo 'there, i.e. if yes then search for user data there).  To generate such '
  echo 'a relay file, e.g. pipe a contacts-list event to: '
  echo "jq --raw-output '.[1].content' | jq '. as \$full | keys | map(. as \$key | {url: ., read: \$full[\$key].read, write: \$full[\$key].write})' > relays.json"
  echo 'If argument not given, will default to `wss://relay.damus.io`.'
  echo
  echo 'Calls `nostr-save-event` on each event, see that script for details.'
  echo
  echo 'If --basedir <dir> given, then use <dir> as base directory to save '
  echo 'events under, rather than the current directory.'
  echo
  echo 'If --pubbasedir <dir> given, then use <dir> as base directory to save '
  echo 'events from other users, rather than the same basedir (see above).'

  exit 0
fi

pubkey="$1"

if [ "$pubkey" == '' ]
then
  echo "Error: no pubkey given, exiting."
  exit 1
fi

shift

# TODO: customizable (and multiple) relays.
# TODO: config option for where to save events

# Query notes:
# We only give the author's pubkey. so this will include all types of notes.
# (Specifically, it will include kind 3 [relay recs], kind 6 [native reposts]
# and kind 7 [reactions].)
queryArgs=('--authors' "$pubkey")

if [ "$1" == '--since' ]
then
  shift
  queryArgs+=('--since' "$(date --date=$1 +%s)")
  shift
fi

relays=(
)

if [ "$1" == '--relays' ]
then
  shift
  relays+=($(jq --raw-output '.[] | select(.write == true) | .url' "$1"))
  shift
else
  relays+=('wss://relay.damus.io')
fi

if [ "$1" == '--basedir' ]
then
  shift
  basedir="$1"
  shift
else
  basedir='.'
fi

nostril-query "${queryArgs[@]}" | \
  nostcat "${relays[@]}" | \
  nostr-save-event "$basedir"

## Repost/Reactions/Replies ##
# TODO: Limit to posts that have just been downloaded (above) if possible.

repostids=(
  # For each JSON file, get `e` tag using `jq`.
  $(find "$basedir" -name '*.json' | xargs --max-args 1 jq --raw-output '.[1].tags | .[] | select(.[0] == "e") | .[1]')
)

allids=$(IFS=$','; echo "${repostids[*]}")

if [ "$1" == '--pubbasedir' ]
then
  shift
  basedir="$1"
  shift
fi

nostril-query -i "$allids" | \
  nostcat "${relays[@]}" | \
  nostr-save-event "$basedir"
