#!/bin/bash
# Launcher script for EA's Origin, running through Wine
# Copyright (C) 2013-2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function myrun() {
  if [ "$1" == "" ]
  then
    echo "Fail"
    return 1
  fi

  #taskset -c 0 "$bin" "$1" >> "$log/origin" 2>&1
  "$bin" "$1" >> "$log/origin" 2>&1
}

validArgs=("bin" "data" "log")

source loadconf "$HOME/.scott_script/wine" "origin.cfg" validArgs[@]

export env WINEPREFIX="$data" WINEARCH=win32

if [ "$1" == "install" ]
then
  echo "First, ensure Wine prefix has been initialized."
  myrun "winecfg"
  echo "Testing winetricks stuff"
  WINE="$bin" winetricks ie8 dotnet30 d3dx9_36 glsl-enable corefonts wininet vcrun2010 gdiplus >> "$log/origin" 2>&1
  echo "Downloading all files"
  wget -O OriginThinSetup.exe "http://www.dm.origin.com/download"
  wget -O qt-setup.exe "http://download.qt-project.org/official_releases/qt/5.1/5.1.1/qt-windows-opensource-5.1.1-mingw48_opengl-x86-offline.exe"
  myrun qt-setup.exe
  echo "Now install"
  myrun OriginThinSetup.exe
else
  cd "/opt/wine/data/origin/drive_c/Program Files/Origin"
  myrun ./Origin.exe
fi
