#!/bin/bash
# Helper script for managing podcast subscriptions.
# Copyright (C) 2022 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

validArgs=('rss_url' 'speed_factor')

function usage() {
  echo 'Usage: podcasts <podcast> <command>'
  echo
  echo 'Where <podcast> is short code matching config file name for podcast.'
  echo
  echo 'Subcommands:'
  echo
  echo '  get-xml'
  echo '  speedup'
  exit 1
}

if [ "$1" == '' ]
then
  usage
fi

# TODO: error checking
podcast="$1"
source loadconf "$HOME/.scott-script/podcasts" "$podcast.cfg" validArgs[@]

if [ "$rss_url" == '' ]
then
  echo "Invalid podcast '$podcast', or 'rss_url' was empty."
  exit 2
fi

xmlfile="$HOME/.scott-script/podcasts/$podcast.xml"
case "$2" in
  get-xml)
    [ "$rss_url" == 'FIXME' ] && exit 3
    wget -O "$xmlfile" "$rss_url"
    ;;
  speedup)
    files="$(ls $podcast-* | grep -v '.fast.mp3' | grep -v '.mp3.orig')"
    for filename in $files
    do
      audio-speedup.sh "$filename" "$speed_factor" || break
    done
    ;;
  # TODO: other commands
  *)
    usage
esac
