#!/bin/bash
# Safely delete a duplicate file.
# Copyright (C) 2022 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

while true
do
  case "$1" in
    --keep)
      shift
      keep="$1"
      shift
      ;;
    --rm)
      shift
      delete="$1"
      shift
      ;;
    *)
      [ "$1" == '' ] && break

      echo "Error, unrecognized argument '$1'"
      echo 'Remember to prefix files with --keep and --rm'
      exit 1
      ;;
  esac
done

if [ "$keep" == '' ]
then
  echo 'Error, missing file to keep.'
  exit 2
fi
if [ "$delete" == '' ]
then
  echo 'Error, missing file to delete.'
  exit 3
fi

diff "$keep" "$delete"
if [ $? -ne 0 ]
then
  echo 'Files differ, see above.'
  exit 4
fi

rm --verbose "$delete"
