#!/bin/bash
# Launcher script for Slack App, running through Wine
# Copyright (C) 2015 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# bin - full path of the Wine executable
# data - Wine prefix folder
# log - log folder

source winesrc "slack"

if [ "$1" == "install" ]
then
  myinitprefix

  myinstall "./SlackSetup.exe"
else
  mydir="drive_c/Program Files/Electronic Arts/Need For Speed World"
  mylaunch "$mydir" "./GameLauncher.exe"
fi
