#!/bin/bash
# Launcher script for Star Wars: The Old Republic, running through Wine
# Copyright (C) 2013 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# bin - full path of the Wine executable
# data - Wine prefix folder
# log - log folder

function myrun() {
  if [ "$1" == "" ]
  then
    echo "Fail"
    return 1
  fi

  "$bin" "$1" >> "$log/swtor" 2>&1
}

validArgs=("bin" "data" "log")

source loadconf "$HOME/.scott_script/wine" "swtor.cfg" validArgs[@]

export env WINEARCH=win32 WINEPREFIX="$data"

if [ "$1" == "install" ]
then
  echo "First, ensure prefix is initialized."
  myrun winecfg
  echo "winetricks d3dx9 vcrun2008 msls31"
  WINE="$bin" winetricks d3dx9 vcrun2008 msls31 >> "$log/swtor" 2>&1
  echo "Now install."
  myrun ./SWTOR_setup.exe
  echo "Should have been successful. If not, check logs and try again."
  echo "Be sure to place swtor_fix.exe in SWTOR program folder."
  #TODO: install swtor_fix automatically
else
  #export WINEDEBUG=+fps
  #cd "$data/drive_c/Program Files/Electronic Arts/BioWare/Star Wars - The Old Republic"
  cd "$data/drive_c/Program Files/Electronic Arts/BioWare/Star Wars-The Old Republic"
  "$bin" ./swtor_fix.exe >> "$log/swtor" 2>&1 &
  "$bin" ./launcher.exe >> "$log/swtor" 2>&1
fi


#Install log:
#WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine winecfg >> /opt/wine/log/swtor 2>&1
#WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine ./SWTOR_setup.exe >> /opt/wine/log/swtor 2>&1
#Install successful
# cd "/opt/wine/data/swtor/drive_c/Program Files/Electronic Arts/BioWare/Star Wars-The Old Republic"
# WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine ./launcher.exe >> /opt/wine/log/swtor 2>&1
# Successful launch, but gives network error.
# Tried again, and it let me log in, but asked for admin perms.
# Apparently it needed Win7 emulation instead of XP.
# Now freezes on splash screen, even with swtor_fix
# WINEPREFIX=/opt/wine/data/swtor WINE=/opt/wine/bin/wine-1.6/wine winetricks d3dx9 >> /opt/wine/log/swtor 2>&1

#Install, attempt 2:
#env WINEARCH=win32 WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine winecfg >> /opt/wine/log/swtor 2>&1
#env WINEARCH=win32 WINEPREFIX=/opt/wine/data/swtor WINE=/opt/wine/bin/wine-1.6/wine winetricks d3dx9 vcrun2008 msls31 >> /opt/wine/log/swtor 2>&1
#env WINEARCH=win32 WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine ./SWTOR_setup.exe >> /opt/wine/log/swtor 2>&1
#cd data/swtor/drive_c/Program\ Files/Electronic\ Arts/BioWare/Star\ Wars\ -\ The\ Old\ Republic/
#env WINEARCH=win32 WINEPREFIX=/opt/wine/data/swtor /opt/wine/bin/wine-1.6/wine ./launcher.exe >> /opt/wine/log/swtor 2>&1
#Win7 emulation, 1920x1080 desktop
#Success!

