#!/bin/bash
# Simple timer script
# Copyright (C) 2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ "$1" != "" ]
then
  minutes=$1
else
  minutes=0
fi

seconds=0

while true
do
  if [ "$seconds" == "60" ]
  then
    minutes=`expr $minutes + 1`
    seconds=0
  fi
  echo "$minutes minute(s) and $seconds second(s)"
  seconds=`expr $seconds + 1`
  sleep 1
done
