#!/bin/bash
# Helper script for Wine
# Copyright (C) 2014 Scott Weldon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case "$1" in
  "kill")
    killall wineserver winedevice.exe explorer.exe services.exe plugplay.exe
    ;;
  "cfg")
    [ -z "$2" ] && "Error, specify which game to run." && exit 1
    source winesrc "$2"
    myrun winecfg
    ;;
  *)
    echo "Error: no such command. TODO: usage."
    ;;
esac
